; Build the service_rpc example against the local Hop library.

[platformio]
src_dir = .

[env]
platform = platformio/espressif32@7.0.1
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
    espressif/toolchain-xtensa-esp32@8.4.0+2021r2-patch5
    espressif/toolchain-riscv32-esp@8.4.0+2021r2-patch5
    platformio/tool-esptoolpy@2.41100.0
    platformio/tool-scons@4.40801.0
framework = arduino
monitor_speed = 115200
lib_deps =
    symlink://../../

[env:esp32dev]
board = esp32dev

[env:esp32c3]
board = esp32-c3-devkitm-1
